/* My Simple Health — Cycle Intelligence V2 */
(function(root){'use strict';
const PREDICTION_MODEL=Object.freeze({name:'MSH_CYCLE_INTERVAL',version:'2.0.0'}),MIN_PATTERN_CYCLES=3;
const INFORMATION_CLASSES=Object.freeze({RECORDED:'RECORDED',ESTIMATED_PREDICTED:'ESTIMATED_PREDICTED',GENERAL_EDUCATION:'GENERAL_EDUCATION',PERSONAL_OBSERVATION:'PERSONAL_OBSERVATION'});
const SYMPTOMS=Object.freeze(['abdominal cramps','back discomfort','cramps','bloating','cravings','headache','breast tenderness','fatigue','anxiety','irritability','lower mood','other']);
const PHASE_EDUCATION=Object.freeze({
 menstrual:{title:'Menstrual phase',summary:'Menstruation begins when the uterine lining is shed.',physiology:'Estrogen and progesterone are typically lower at the start of bleeding. FSH begins supporting new ovarian follicles.',experiences:'Some people notice cramping, fatigue, appetite changes, or no distinct change.'},
 follicular:{title:'Follicular phase',summary:'Follicles develop as the body prepares for a possible ovulation.',physiology:'FSH supports follicular development. Estrogen typically rises as a dominant follicle develops and the endometrium rebuilds.',experiences:'Some people notice changing energy, mood, or cervical mucus; others notice very little.'},
 'ovulatory window':{title:'Estimated ovulatory window',summary:'Calendar history can estimate when ovulation may be more likely, but cannot confirm it occurred.',physiology:'In a typical ovulatory cycle, rising estrogen is followed by an LH surge that helps trigger ovulation. Timing varies.',experiences:'Some people notice slippery cervical mucus, libido changes, or mild discomfort; none alone confirms ovulation.'},
 luteal:{title:'Luteal phase',summary:'After ovulation, the corpus luteum typically produces progesterone.',physiology:'Progesterone generally rises and supports the endometrium. Estrogen and progesterone typically fall before menstruation.',experiences:'Some people notice breast tenderness, appetite, mood, sleep, or energy changes; experiences vary widely.'}
});
const list=v=>Array.isArray(v)?v:[],pad=v=>String(v).padStart(2,'0'),clean=(v,n=240)=>String(v==null?'':v).trim().slice(0,n),num=v=>Number.isFinite(Number(v))?Number(v):null;
function toDateKey(v){if(typeof v==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(v))return v;const d=v instanceof Date?v:new Date(v);return Number.isFinite(d.getTime())?`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`:''}
function parseDate(k){const m=/^(\d{4})-(\d{2})-(\d{2})$/.exec(k||'');return m?new Date(+m[1],+m[2]-1,+m[3],12):new Date(NaN)}
function addDays(k,n){const d=parseDate(k);d.setDate(d.getDate()+n);return toDateKey(d)}function daysBetween(a,b){return Math.round((parseDate(b)-parseDate(a))/86400000)}
const mean=a=>a.length?a.reduce((s,v)=>s+v,0)/a.length:null;function sd(a){if(a.length<2)return null;const m=mean(a);return Math.sqrt(a.reduce((s,v)=>s+(v-m)**2,0)/(a.length-1))}
function getCalendar(s){return s&&s.calendar||{events:[],predictions:[],settings:{cycle:{}},privacy:{}}}
function normalizeDailyValue(v){const s=v&&typeof v==='object'?v:{},m=s.moodExperience||{},r=s.sexualReproductive||{},z=s.measurements||{},c=s.care||{},raw=list(s.symptoms).map(x=>clean(x,80).toLowerCase());return{bleeding:['none','spotting','light','medium','heavy'].includes(s.bleeding)?s.bleeding:'none',periodMarker:['start','end','ongoing','none'].includes(s.periodMarker)?s.periodMarker:'none',discharge:clean(s.discharge,120),symptoms:[...new Set(raw.filter(x=>SYMPTOMS.includes(x)))],otherSymptoms:[...new Set([...list(s.otherSymptoms),...raw.filter(x=>!SYMPTOMS.includes(x))].map(x=>clean(x,80)).filter(Boolean))],noSymptoms:s.noSymptoms===true,moodExperience:{anxiety:clean(m.anxiety||s.anxiety,40),irritability:clean(m.irritability,40),mood:clean(m.mood||s.mood,80),energy:clean(m.energy||s.energy,40),sleep:clean(m.sleep||s.sleep,80),libido:clean(m.libido||s.libido,40)},sexualReproductive:{sexualActivity:clean(r.sexualActivity,40),protection:clean(r.protection,80),contraception:clean(r.contraception,120),context:clean(r.context||s.reproductiveHealth,300)},measurements:{temperature:num(z.temperature),temperatureUnit:z.temperatureUnit==='C'?'C':'F',weight:num(z.weight),weightUnit:z.weightUnit==='kg'?'kg':'lb'},care:{medication:clean(c.medication||s.medication,180),painRelief:clean(c.painRelief,180),notes:clean(c.notes,300)},note:clean(s.note,1600)}}
function prov(status,id){return root.MSHStorage?.createProvenance?root.MSHStorage.createProvenance(status,{sourceId:id}):{status,sourceId:id,recordedAt:new Date().toISOString(),transitions:[]}}
function recordedCycleEvents(s){return list(getCalendar(s).events).filter(e=>e&&e.category==='cycle'&&e.recordStatus==='recorded').map(e=>({...e,value:normalizeDailyValue(e.value)}))}
function dailyObservation(s,d){return recordedCycleEvents(s).find(e=>e.type==='cycle_day_observation'&&e.date===d)||null}function periodDays(s){return recordedCycleEvents(s).filter(e=>!['none','spotting'].includes(e.value.bleeding)).map(e=>e.date).sort()}
function periodSegments(s){const out=[];[...new Set(periodDays(s))].forEach(d=>{const c=out.at(-1);if(!c||daysBetween(c.end,d)>1)out.push({start:d,end:d,days:[d]});else{c.end=d;c.days.push(d)}});return out}
function makeEvent(date,value,o={}){const t=o.timestamp||new Date().toISOString(),id=o.id||(root.MSHStorage?root.MSHStorage.uid('calendar'):`calendar_${Date.now()}`);return{id,category:'cycle',type:'cycle_day_observation',date,timestamp:t,recordStatus:'recorded',informationClass:INFORMATION_CLASSES.RECORDED,source:{type:o.sourceType||'USER_ENTRY',channel:o.channel||'cycle_calendar'},prediction:null,value:normalizeDailyValue(value),userStatedContext:clean(o.userStatedContext,500),provenance:prov('USER_STATED',id),createdAt:o.createdAt||t,updatedAt:t}}
function saveDailyObservation(date,value,o){const k=toDateKey(date);if(!k||!root.MSHStorage)return null;let saved;root.MSHStorage.updateState(s=>{const old=s.calendar.events.find(e=>e.category==='cycle'&&e.type==='cycle_day_observation'&&e.date===k);saved=makeEvent(k,value,{...(o||{}),id:old?.id,createdAt:old?.createdAt});if(old)s.calendar.events.splice(s.calendar.events.indexOf(old),1,saved);else s.calendar.events.push(saved);s.calendar.predictions=calculatePredictions(s);return s});return saved}
function removeDailyObservation(date){const k=toDateKey(date);if(!root.MSHStorage||!k)return false;let ok=false;root.MSHStorage.updateState(s=>{const n=s.calendar.events.length;s.calendar.events=s.calendar.events.filter(e=>!(e.category==='cycle'&&e.type==='cycle_day_observation'&&e.date===k));ok=n!==s.calendar.events.length;s.calendar.predictions=calculatePredictions(s);return s});return ok}
function recordPeriod(a,b,flow,o){const start=toDateKey(a),end=toDateKey(b||a);if(!start||!end||daysBetween(start,end)<0||daysBetween(start,end)>14)return[];const out=[];for(let d=start;daysBetween(d,end)>=0;d=addDays(d,1)){const old=root.MSHStorage&&dailyObservation(root.MSHStorage.getState(),d);out.push(saveDailyObservation(d,{...(old?.value||{}),bleeding:flow||'medium',periodMarker:d===start?'start':d===end?'end':'ongoing'},o))}return out}
function cycleForDate(s,d){const seg=periodSegments(s),start=[...seg].reverse().find(x=>x.start<=d);return start?{start:start.start,cycleDay:daysBetween(start.start,d)+1}:null}
function calculateStats(s){const seg=periodSegments(s),starts=seg.map(x=>x.start),lengths=starts.slice(1).map((x,i)=>daysBetween(starts[i],x)).filter(x=>x>=15&&x<=60),period=seg.map(x=>x.days.length),frequency={},series={energy:[],mood:[],libido:[],temperature:[],weight:[]};recordedCycleEvents(s).forEach(e=>{[...e.value.symptoms,...e.value.otherSymptoms].forEach(x=>frequency[x]=(frequency[x]||0)+1);const c=cycleForDate(s,e.date),base={date:e.date,cycleDay:c?.cycleDay,recordId:e.id};for(const k of ['energy','mood','libido'])if(e.value.moodExperience[k])series[k].push({...base,value:e.value.moodExperience[k]});for(const k of ['temperature','weight'])if(e.value.measurements[k]!=null)series[k].push({...base,value:e.value.measurements[k],unit:e.value.measurements[k+'Unit']})});return{recordedCycles:seg.length,completedCycleIntervals:lengths.length,averageCycleLength:lengths.length?Math.round(mean(lengths)*10)/10:null,observedCycleRange:lengths.length?[Math.min(...lengths),Math.max(...lengths)]:null,cycleVariability:lengths.length>1?Math.round(sd(lengths)*10)/10:null,averagePeriodLength:period.length?Math.round(mean(period)*10)/10:null,recentCycles:seg.slice(-6),cycleLengths:lengths,periodLengths:period,symptomFrequency:frequency,variableSeries:series}}
function pred(type,a,b,ids,u,t){return{id:`cycle_prediction_${type}_${a}`,category:'cycle',type,startDate:a,endDate:b||a,recordStatus:'predicted',informationClass:INFORMATION_CLASSES.ESTIMATED_PREDICTED,source:{type:'SYSTEM_CALCULATION',channel:'cycle_calendar'},prediction:{model:PREDICTION_MODEL.name,version:PREDICTION_MODEL.version,generatedAt:t,sourceCycleIds:ids,confidence:ids.length>=4?'moderate':'low',uncertaintyDays:u},provenance:prov('SYSTEM_OBSERVED',`cycle_prediction_${type}_${a}`)}}
function calculatePredictions(s,o={}){const seg=periodSegments(s);if(!seg.length)return[];const st=calculateStats(s),interval=Math.round(st.averageCycleLength||28),u=st.observedCycleRange?Math.max(2,Math.ceil((st.observedCycleRange[1]-st.observedCycleRange[0])/2)):4,next=addDays(seg.at(-1).start,interval),ids=seg.slice(-6).map(x=>x.start),t=o.generatedAt||new Date().toISOString(),ov=addDays(next,-14);const out=[pred('predicted_period',next,addDays(next,Math.round(st.averagePeriodLength||5)-1),ids,u,t)];if(seg.length>=2)out.push(pred('estimated_fertile_window',addDays(ov,-5),ov,ids,u+2,t),pred('estimated_ovulation',ov,ov,ids,u+2,t));return out}
function estimatedStatus(s,date){const c=cycleForDate(s,toDateKey(date));if(!c)return{cycleDay:null,phase:null,estimated:true,confidence:'insufficient'};const st=calculateStats(s),avg=Math.round(st.averageCycleLength||28),day=c.cycleDay,phase=day<=Math.round(st.averagePeriodLength||5)?'menstrual':day<Math.max(8,avg-16)?'follicular':day<=avg-12?'ovulatory window':'luteal';return{cycleDay:day,phase,estimated:true,confidence:st.completedCycleIntervals>=3?'moderate':'low'}}
function getStatusViewModel(s,date){const k=toDateKey(date),e=dailyObservation(s,k),status=estimatedStatus(s,k),p=getCalendar(s).predictions||[],next=p.find(x=>x.type==='predicted_period'&&x.startDate>=k),fert=p.find(x=>x.type==='estimated_fertile_window'&&k>=x.startDate&&k<=x.endDate);return{date:k,cycleDay:status.cycleDay,estimatedPhase:status.phase,confidence:status.confidence,periodRecorded:Boolean(e&&!['none','spotting'].includes(e.value.bleeding)),periodEstimate:next?{date:next.startDate,daysAway:daysBetween(k,next.startDate),confidence:next.prediction.confidence}:null,fertileEstimate:fert?{active:true,label:k===fert.endDate?'Higher estimated fertility today':'Estimated fertile window',confidence:fert.prediction.confidence}:null}}
function relative(s,fn){const ev=recordedCycleEvents(s),seg=periodSegments(s);return seg.map((x,i)=>({cycleStart:x.start,records:ev.filter(e=>e.date>=x.start&&e.date<=(seg[i+1]?addDays(seg[i+1].start,-1):addDays(x.start,35))&&fn(e)).map(e=>({event:e,cycleDay:daysBetween(x.start,e.date)+1}))}))}
function obs(id,text,cycles,records,timing,uncertainty){return{id,statement:text,informationClass:INFORMATION_CLASSES.PERSONAL_OBSERVATION,epistemicStatus:'SYSTEM_OBSERVED',cyclesIncluded:cycles.length,cyclesObserved:cycles.filter(c=>c.records.length).length,observationWindow:{start:cycles[0].cycleStart,end:cycles.at(-1).cycleStart},sourceData:records.map(r=>r.event.id),cycleRelativeTiming:timing,uncertainty,threshold:{minimumCycles:3,minimumRepeatedCycles:2},diagnosis:false,causalClaim:false}}
function calculatePatterns(s){const seg=periodSegments(s);if(seg.length<3)return[];const out=[],cr=relative(s,e=>e.value.symptoms.some(x=>['cramps','abdominal cramps'].includes(x))),crr=cr.flatMap(c=>c.records.filter(r=>r.cycleDay<=2)),crc=cr.filter(c=>c.records.some(r=>r.cycleDay<=2)).length;if(crc>=2)out.push(obs('pattern_cramps_early',`Cramps were recorded during the first two cycle days in ${crc} of your last ${seg.length} recorded cycles.`,cr,crr,'cycle days 1–2','Based on recorded starts; unrecorded days may be missing.'));const en=relative(s,e=>e.value.moodExperience.energy==='lower'||e.value.symptoms.includes('fatigue')),enr=en.flatMap(c=>c.records.filter(r=>r.cycleDay>=23&&r.cycleDay<=32)),enc=en.filter(c=>c.records.some(r=>r.cycleDay>=23&&r.cycleDay<=32)).length;if(enc>=2)out.push(obs('pattern_energy_late',`Lower energy was recorded around cycle days 23–32 in ${enc} of your last ${seg.length} recorded cycles.`,en,enr,'cycle days 23–32','Descriptive timing; no hormonal cause is established.'));const li=relative(s,e=>e.value.moodExperience.libido==='higher'),lir=li.flatMap(c=>c.records.filter(r=>r.cycleDay>=8&&r.cycleDay<=18)),lic=li.filter(c=>c.records.some(r=>r.cycleDay>=8&&r.cycleDay<=18)).length;if(lic>=2)out.push(obs('pattern_libido_window',`Higher libido appeared near the estimated fertile window in ${lic} recorded cycles${lic<seg.length?', but it has not been consistent':''}.`,li,lir,'cycle days 8–18','Calendar-estimated; libido does not confirm ovulation.'));return out}
function getPhaseEducation(p){return PHASE_EDUCATION[p]?{...PHASE_EDUCATION[p],informationClass:INFORMATION_CLASSES.GENERAL_EDUCATION,measured:false,label:'Typical hormone pattern · educational illustration'}:null}
function updatePrivacy(p){if(!root.MSHStorage)return null;return root.MSHStorage.updateState(s=>{for(const k of ['workspace','hello','patternAnalysis'])if(typeof p[k]==='boolean')s.calendar.privacy[k]=p[k];s.calendar.privacy.cycleCalendar=true;return s}).calendar.privacy}
function proposeControlledAction(m,today){const t=clean(m,400);if(!/^(?:please\s+)?(?:add|log|record)\s+my\s+period\b/i.test(t))return null;const x=t.match(/\b(\d{4}-\d{2}-\d{2})\b/),d=x?x[1]:/\b(?:today|starting today)\b/i.test(t)?toDateKey(today||new Date()):'';return d?{type:'RECORD_PERIOD_START',date:d,bleeding:'medium',requiresExplicitUserInstruction:true}:null}
function executeControlledAction(a){if(!a||a.type!=='RECORD_PERIOD_START'||!toDateKey(a.date))return{ok:false,reason:'INVALID_ACTION'};const s=root.MSHStorage?.getState();if(!s||s.calendar.privacy.hello!==true)return{ok:false,reason:'HELLO_ACCESS_DISABLED'};const e=saveDailyObservation(a.date,{bleeding:a.bleeding||'medium',periodMarker:'start'},{sourceType:'HELLO_CONTROLLED_ACTION',channel:'hello'});return{ok:Boolean(e),event:e,message:`Period recorded for ${parseDate(a.date).toLocaleDateString(undefined,{month:'long',day:'numeric',year:'numeric'})}.`}}
function createSyntheticDemoState(base,today){const s=JSON.parse(JSON.stringify(base||{}));s.calendar=s.calendar||{};s.calendar.events=[];s.calendar.predictions=[];const anchor=toDateKey(today||new Date()),starts=[-112,-84,-56,-28,0].map(x=>addDays(anchor,x));let n=0;const add=(date,value)=>{const id=`synthetic_cycle_${++n}`;s.calendar.events.push({...makeEvent(date,value,{id,timestamp:`${date}T12:00:00.000Z`,sourceType:'SYNTHETIC_QA'}),synthetic:true})};starts.forEach((st,i)=>{for(let d=0;d<4+(i%2);d++)add(addDays(st,d),{bleeding:d===0?'heavy':d===1?'medium':'light',periodMarker:d===0?'start':'ongoing',symptoms:d<2?['cramps','fatigue']:[],moodExperience:{energy:d<2?'lower':'steady'},care:{painRelief:d===0&&i>1?'Pain relief recorded':''}});add(addDays(st,12),{moodExperience:{energy:'higher',libido:i===1?'steady':'higher'},discharge:'slippery'});add(addDays(st,25),{symptoms:i===2?[]:['fatigue'],moodExperience:{energy:i===2?'steady':'lower'},measurements:{temperature:98.1+i*.05}})});s.calendar.predictions=calculatePredictions(s,{generatedAt:`${anchor}T12:00:00.000Z`});s.calendar.privacy={cycleCalendar:true,workspace:false,hello:true,patternAnalysis:true};s.calendar.demo={synthetic:true,label:'Synthetic QA demo · not saved'};return s}
root.MSHCycle=Object.freeze({PREDICTION_MODEL,MIN_PATTERN_CYCLES,INFORMATION_CLASSES,SYMPTOMS,PHASE_EDUCATION,toDateKey,addDays,daysBetween,getCalendar,normalizeDailyValue,recordedCycleEvents,dailyObservation,periodDays,periodSegments,saveDailyObservation,removeDailyObservation,recordPeriod,calculateStats,calculatePredictions,estimatedStatus,getStatusViewModel,calculatePatterns,getPhaseEducation,updatePrivacy,proposeControlledAction,executeControlledAction,createSyntheticDemoState});
})(typeof window!=='undefined'?window:globalThis);
