import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import test from 'node:test';
import vm from 'node:vm';
const storage=await readFile(new URL('../js/msh-storage.js',import.meta.url),'utf8');
const cycle=await readFile(new URL('../js/msh-cycle.js',import.meta.url),'utf8');
const ui=await readFile(new URL('../js/msh-calendar.js',import.meta.url),'utf8');
const css=await readFile(new URL('../css/msh-cycle.css',import.meta.url),'utf8');
function app(){const mem=new Map(),s={console,Date,Math,crypto:{randomUUID:()=>String(Math.random())},localStorage:{getItem:k=>mem.get(k)||null,setItem:(k,v)=>mem.set(k,String(v)),removeItem:k=>mem.delete(k)},sessionStorage:{removeItem(){}}};s.window=s;s.globalThis=s;vm.runInNewContext(storage,s);vm.runInNewContext(cycle,s);return s}
test('expanded daily observations remain optional, structured, and provenance-safe',()=>{const a=app(),e=a.MSHCycle.saveDailyObservation('2026-08-25',{bleeding:'spotting',otherSymptoms:['pelvic pressure'],moodExperience:{anxiety:'higher',energy:'lower',libido:'higher'},sexualReproductive:{sexualActivity:'recorded',contraception:'user-entered'},measurements:{temperature:98.2,weight:150},care:{painRelief:'user-entered'}});assert.equal(e.informationClass,'RECORDED');assert.equal(e.provenance.status,'USER_STATED');assert.equal(e.value.measurements.temperature,98.2);assert.equal(e.value.sexualReproductive.sexualActivity,'recorded');assert.deepEqual(Array.from(e.value.otherSymptoms),['pelvic pressure'])});
test('predictions include estimated ovulation without claiming confirmed ovulation',()=>{const a=app();['2026-05-01','2026-05-29','2026-06-26'].forEach(d=>a.MSHCycle.recordPeriod(d,a.MSHCycle.addDays(d,3),'medium'));const p=a.MSHStorage.getState().calendar.predictions;assert.ok(p.some(x=>x.type==='estimated_ovulation'));assert.ok(p.every(x=>x.recordStatus==='predicted'&&x.informationClass==='ESTIMATED_PREDICTED'));assert.ok(p.every(x=>!/confirmed/i.test(JSON.stringify(x))))});
test('phase education is explicitly typical and never represented as measured',()=>{const a=app(),e=a.MSHCycle.getPhaseEducation('luteal');assert.equal(e.informationClass,'GENERAL_EDUCATION');assert.equal(e.measured,false);assert.match(e.label,/educational illustration/i);assert.match(ui,/Hormone levels were not measured/)});
test('longitudinal observations retain sample, timing, sources, and uncertainty',()=>{const a=app();['2026-05-01','2026-05-29','2026-06-26','2026-07-24'].forEach(d=>{a.MSHCycle.recordPeriod(d,a.MSHCycle.addDays(d,3),'medium');a.MSHCycle.saveDailyObservation(d,{bleeding:'heavy',symptoms:['cramps']});a.MSHCycle.saveDailyObservation(a.MSHCycle.addDays(d,25),{moodExperience:{energy:'lower'}})});const p=a.MSHCycle.calculatePatterns(a.MSHStorage.getState());assert.ok(p.length>=2);assert.ok(p.every(x=>x.cyclesIncluded>=3&&x.sourceData.length>=2&&x.cycleRelativeTiming&&x.uncertainty));assert.ok(p.every(x=>!x.diagnosis&&!x.causalClaim))});
test('editing and removing records recalculates patterns and statistics',()=>{const a=app();['2026-05-01','2026-05-29','2026-06-26'].forEach(d=>{a.MSHCycle.recordPeriod(d,a.MSHCycle.addDays(d,3),'medium');a.MSHCycle.saveDailyObservation(d,{bleeding:'heavy',symptoms:['cramps']})});assert.ok(a.MSHCycle.calculatePatterns(a.MSHStorage.getState()).length);for(let d=0;d<4;d++)a.MSHCycle.removeDailyObservation(a.MSHCycle.addDays('2026-06-26',d));assert.equal(a.MSHCycle.calculateStats(a.MSHStorage.getState()).recordedCycles,2);assert.equal(a.MSHCycle.calculatePatterns(a.MSHStorage.getState()).length,0)});
test('synthetic demonstration data is isolated and unmistakably labelled',()=>{const a=app(),base=a.MSHStorage.getState(),demo=a.MSHCycle.createSyntheticDemoState(base,new Date(2026,7,25));assert.equal(a.MSHStorage.getState().calendar.events.length,0);assert.ok(demo.calendar.events.every(x=>x.synthetic&&x.source.type==='SYNTHETIC_QA'));assert.match(demo.calendar.demo.label,/Synthetic QA demo.*not saved/);assert.match(ui,/demo=cycle-v2|Synthetic QA demo/)});
test('V2 interface exposes information classes, visual controls, analytics, and education',()=>{for(const word of ['Recorded','Estimated / predicted','General education','Personal observation'])assert.match(ui,new RegExp(word));assert.match(css,/msh-cycle-ring/);assert.match(css,/msh-cycle-picture-choice/);assert.match(css,/msh-cycle-charts/);assert.match(ui,/should not be relied upon as contraception/);assert.doesNotMatch(ui,/normal cycle|abnormal cycle/i)});
